import { Colors } from '@/constants/Colors';
import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'flex-start',
    marginTop: 32,
    padding: 12,
  },
  headerContainer: {
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
  },
  status: {
    fontSize: 24,
    fontWeight: '400',
    letterSpacing: 2,
    textTransform: 'uppercase',
    color: '#FFFFFF',
    textAlign: 'center',
    textShadowColor: 'rgba(0, 0, 0, 0.1)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  timerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
    marginTop: 0,
    marginBottom: 0,
  },
  timerStatus: {
    textTransform: 'uppercase',
    marginBottom: 4,
    letterSpacing: 1,
    fontSize: 14,
    opacity: 0.9,
  },
  timerContainer: {
    borderWidth: 5,
    borderColor: Colors.light.primary,
    borderRadius: 120,
    width: 240,
    height: 240,
    alignItems: 'center',
    justifyContent: 'center',
    marginVertical: 12,
    backgroundColor: 'rgba(255, 192, 203, 0.05)',
    shadowColor: Colors.light.primary,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 8,
    position: 'relative',
  },
  timer: {
    fontSize: 52,
    fontWeight: '300',
    textAlign: 'center',
    letterSpacing: 2,
    includeFontPadding: false,
    lineHeight: 56,
  },
  adjustButton: {
    width: 28,
    height: 28,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: Colors.light.primary,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.12,
    shadowRadius: 4,
    elevation: 2,
  },
  adjustButtonText: {
    color: '#fff',
    fontSize: 20,
    fontWeight: '300',
    includeFontPadding: false,
    textAlign: 'center',
    lineHeight: 24,
  },
  bottomContainer: {
    width: '100%',
    borderWidth: 1,
    borderColor: '#321f29',
    marginTop: 10,
    backgroundColor: '#1e0d15',
    borderRadius: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -3 },
    shadowOpacity: 0.2,
    shadowRadius: 12,
    elevation: 10,
  },
  controlsRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 16,
    marginBottom: 32,
  },
  button: {
    paddingHorizontal: 32,
    paddingVertical: 12,
    borderRadius: 25,
    minWidth: 120,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: Colors.light.primary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 4,
  },
  buttonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  audioBar: {
    width: '100%',
    paddingVertical: 12,
  },
  audioControls: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingHorizontal: 8,
  },
  musicMenuButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
  },
  playPauseButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
  },
  iconText: {
    fontSize: 20,
    color: '#fff',
    lineHeight: 24,
    textAlign: 'center',
    fontWeight: '600',
    textAlignVertical: 'center',
    includeFontPadding: false,
  },
  modalOverlay: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },  soundMenu: {
    padding: 24,
    borderRadius: 20,
    width: '85%',
    maxWidth: 320,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.3,
    shadowRadius: 16,
    elevation: 10,
    gap: 16,
  },
  menuTitle: {
    fontSize: 24,
    textAlign: 'center',
    marginBottom: 4,
    textShadowColor: 'rgba(0, 0, 0, 0.1)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  menuSubtitle: {
    fontSize: 14,
    opacity: 0.8,
    textAlign: 'center',
    marginBottom: 8,
    letterSpacing: 0.5,
  },
  menuDivider: {
    height: 1,
    backgroundColor: '#fff',
    opacity: 0.15,
    marginBottom: 8,
  },
  menuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 16,
    borderRadius: 12,
    gap: 16,
    marginVertical: 4,
  },
  selectedMenuItem: {
    transform: [{ scale: 1.02 }],
  },
  menuItemIcon: {
    fontSize: 24,
    textShadowColor: 'rgba(0, 0, 0, 0.2)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  menuItemLabel: {
    fontSize: 16,
    letterSpacing: 0.5,
  },
  sliderContainer: {
    width: '100%',
    paddingHorizontal: 8,
    marginTop: 4,
  },
  volumeSlider: {
    flex: 1,
    marginHorizontal: 8,
  },
  sliderTrack: {
    height: 4,
    borderRadius: 2,
  },
  volumeIcons: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 12,
    marginBottom: 4,
  },
  volumeIcon: {
    fontSize: 16,
    opacity: 0.7,
  },
  progressContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: 16,
    marginBottom: 32,
    gap: 8,
  },
  progressDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    shadowColor: Colors.light.primary,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.12,
    shadowRadius: 1,
    elevation: 1,
  },
  progressBarWrapper: {
    width: '40%',
    alignSelf: 'center',
    marginTop: 5,
  },
  progressBarBackground: {
    width: '100%',
    height: 2,
    borderRadius: 3,
    backgroundColor: Colors.light.secondary,
    overflow: 'hidden',
  },
  progressBarFill: {
    height: 2,
    borderRadius: 3,
    backgroundColor: Colors.light.accent,
  },
  musicSelector: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 12,
    paddingHorizontal: 16,
    minHeight: 60,
  },
  musicInfo: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  musicControls: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  playButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: Colors.light.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  dropdownButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#2c1120', // Hot pink
    alignItems: 'center',
    justifyContent: 'center',
  },
  dropdownText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '500',
    textAlign: 'center',
    includeFontPadding: false,
  },
  volumeContainer: {
    backgroundColor: '#2c1120',
    borderRadius: 12,
    padding: 16,
    marginTop: 8,
    marginHorizontal: 16,
  },
  volumeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 1,
    width: '80%',
  },
  volumeSlider: {
    flex: 1,
    width: '100%',
  },
  volumeText: {
    color: '#FFFFFF',
    fontSize: 14,
    opacity: 0.8,
    minWidth: 40,
    textAlign: 'right',
  },
});
